// Verse text loading from pre-bundled JSON
// Generated by: npx tsx scripts/bundle-texts.ts

export interface VerseText {
  he: string;
  en: string;
}

export type VerseTexts = Record<string, Record<string, Record<string, VerseText>>>;
// Structure: { [book]: { [chapter]: { [verse]: { he, en } } } }

export async function loadAllVerseTexts(): Promise<VerseTexts> {
  const response = await fetch(
    `${import.meta.env.BASE_URL}data/all-texts.json`
  );

  if (!response.ok) {
    console.error(`Failed to load verse texts: ${response.status}`);
    return {};
  }

  const verseTexts: VerseTexts = await response.json();
  return verseTexts;
}

export function getVerseText(
  verseTexts: VerseTexts,
  book: string,
  chapter: number,
  verse: number
): VerseText | null {
  return verseTexts[book]?.[String(chapter)]?.[String(verse)] || null;
}
