// Data loading: Tanakh structure and verse texts
// Verse texts generated by: npx tsx scripts/bundle-texts.ts

import type { TorahData } from './types.ts';
import { fetchData } from './constants.ts';
import { loadJson } from './loadJson.ts';

export interface VerseText {
  he: string;
  en: string;
}

export type VerseTexts = Record<string, Record<string, Record<string, VerseText>>>;
// Structure: { [book]: { [chapter]: { [verse]: { he, en } } } }

export const STRUCTURE_FILE = 'tanakh-structure.json';
export const TEXTS_FILE = 'all-texts.json';

export async function loadTanakhStructure(): Promise<TorahData> {
  const response = await fetchData(STRUCTURE_FILE);

  if (!response.ok) {
    throw new Error(`Failed to load tanakh-structure.json: ${response.status}`);
  }

  return await response.json();
}

export async function loadAllVerseTexts(): Promise<VerseTexts> {
  return (await loadJson<VerseTexts>(TEXTS_FILE, 'verse texts')) ?? {};
}

export function getVerseText(
  verseTexts: VerseTexts,
  book: string,
  chapter: number,
  verse: number,
): VerseText | null {
  return verseTexts[book]?.[String(chapter)]?.[String(verse)] || null;
}
