// Data loading: Tanakh structure and verse texts
// Verse texts generated by: npx tsx scripts/bundle-texts.ts

import type { TorahData } from "./types.ts";
import { dataPath } from "./constants/app.ts";

export interface VerseText {
  he: string;
  en: string;
}

export type VerseTexts = Record<string, Record<string, Record<string, VerseText>>>;
// Structure: { [book]: { [chapter]: { [verse]: { he, en } } } }

export async function loadTanakhStructure(): Promise<TorahData> {
  const response = await fetch(dataPath("tanakh-structure.json"));

  if (!response.ok) {
    throw new Error(`Failed to load tanakh-structure.json: ${response.status}`);
  }

  return await response.json();
}

export async function loadAllVerseTexts(): Promise<VerseTexts> {
  const response = await fetch(dataPath("all-texts.json"));

  if (!response.ok) {
    console.error(`Failed to load verse texts: ${response.status}`);
    return {};
  }

  const verseTexts: VerseTexts = await response.json();
  return verseTexts;
}

export function getVerseText(
  verseTexts: VerseTexts,
  book: string,
  chapter: number,
  verse: number
): VerseText | null {
  return verseTexts[book]?.[String(chapter)]?.[String(verse)] || null;
}
